name: Generate Snake
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: output
          path: output

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: HellBee404
          svg_out_path: output/snake.svg
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output
        run: |
          cd output
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake.svg
         
