name: Generate Snake
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: HellBee404
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
